/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/vehicles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all vehicles with optional filters */
        get: operations["VehiclesController_findAll"];
        put?: never;
        /** Create a new vehicle */
        post: operations["VehiclesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vehicles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a vehicle by ID */
        get: operations["VehiclesController_findOne"];
        put?: never;
        post?: never;
        /** Delete a vehicle */
        delete: operations["VehiclesController_remove"];
        options?: never;
        head?: never;
        /** Update a vehicle */
        patch: operations["VehiclesController_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateVehicleDto: {
            /**
             * @description The brand of the vehicle
             * @example Toyota
             */
            brand: string;
            /**
             * @description The model of the vehicle
             * @example Camry
             */
            model: string;
            /**
             * @description The license plate number
             * @example ABC-123
             */
            plateNumber: string;
            /**
             * @description The year of manufacture
             * @example 2023
             */
            year: number;
            /**
             * @description The current status of the vehicle
             * @example available
             * @enum {string}
             */
            status?: "available" | "in_use" | "maintenance";
        };
        Vehicle: {
            /**
             * @description Unique identifier
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            id: string;
            /**
             * @description The brand of the vehicle
             * @example Toyota
             */
            brand: string;
            /**
             * @description The model of the vehicle
             * @example Camry
             */
            model: string;
            /**
             * @description The license plate number
             * @example ABC-123
             */
            plateNumber: string;
            /**
             * @description The year of manufacture
             * @example 2023
             */
            year: number;
            /**
             * @description The current status of the vehicle
             * @example available
             * @enum {string}
             */
            status: "available" | "in_use" | "maintenance";
            /**
             * Format: date-time
             * @description The date when the vehicle was created
             * @example 2024-01-15T10:30:00Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description The date when the vehicle was last updated
             * @example 2024-01-15T10:30:00Z
             */
            updatedAt: string;
        };
        UpdateVehicleDto: {
            /**
             * @description The brand of the vehicle
             * @example Toyota
             */
            brand?: string;
            /**
             * @description The model of the vehicle
             * @example Camry
             */
            model?: string;
            /**
             * @description The license plate number
             * @example ABC-123
             */
            plateNumber?: string;
            /**
             * @description The year of manufacture
             * @example 2023
             */
            year?: number;
            /**
             * @description The current status of the vehicle
             * @example available
             * @enum {string}
             */
            status?: "available" | "in_use" | "maintenance";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    VehiclesController_findAll: {
        parameters: {
            query?: {
                /** @description Filter by vehicle brand */
                brand?: string;
                /** @description Filter by vehicle model */
                model?: string;
                /** @description Filter by year of manufacture */
                year?: number;
                /** @description Filter by vehicle status */
                status?: "available" | "in_use" | "maintenance";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Return all vehicles matching the filters */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vehicle"][];
                };
            };
            /** @description Invalid filter parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    VehiclesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateVehicleDto"];
            };
        };
        responses: {
            /** @description Vehicle successfully created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vehicle"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    VehiclesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Vehicle UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Return the vehicle */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vehicle"];
                };
            };
            /** @description Invalid UUID format */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Vehicle not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    VehiclesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Vehicle UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Vehicle successfully deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Vehicle not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    VehiclesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Vehicle UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateVehicleDto"];
            };
        };
        responses: {
            /** @description Vehicle successfully updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vehicle"];
                };
            };
            /** @description Invalid input data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Vehicle not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
